copy files instead of moving to fix Docker problem (#20)
* copy files instead of moving to fix Docker problem

* add check for compilation before push

Co-authored-by: Nicolas Sauvage <nicolas.sauvage@talan.com>

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -31,3 +31,12 @@ else
   echo "Frontend lint failed"
   exit 1
 fi
+
+echo "Compile frontend"
+npm run compile
+if test $? -eq 0; then
+  echo "Backend compilation success"
+else
+  echo "Backend compilation failed"
+  exit 1
+fi
