fix(lint): fix linter errors in frontend

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -3,14 +3,14 @@ echo "Running pre-push hook..."
 
 cd back || exit 1
 
-#echo "Lint backend"
-#npm run lint -- --max-warnings 0
-#if test $? -eq 0; then
-#  echo "Backend lint success"
-#else
-#  echo "Backend lint failed"
-#  exit 1
-#fi
+echo "Lint backend"
+npm run lint -- --max-warnings 0
+if test $? -eq 0; then
+  echo "Backend lint success"
+else
+  echo "Backend lint failed"
+  exit 1
+fi
 
 echo "Check backend dependencies"
 npm run check-architecture
